sudo: true
os: linux
language: go
go: ["1.11"]

env:
  global:
    - BUILD_COMMIT=$TRAVIS_COMMIT
    - BUILD_BRANCH=$TRAVIS_BRANCH
    - BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
    - BUILD_VERSION=$TRAVIS_TAG

before_install:
  - if [ -z "$BUILD_VERSION" ]; then
      export BUILD_VERSION=$(
        curl -s -H "Authorization:token $GIT_RELEASES_API_KEY"
        https://api.github.com/repos/${TRAVIS_REPO_SLUG}/releases |
        jq -r '( first(.[]  | select(.prerelease == true)) ) | .tag_name');
    fi

cache:
  directories:
    - vendor

stages:
  - test

jobs:
  include:
    # Test stage
    - stage: test
      script:
      - go get github.com/go-swagger/go-swagger/cmd/swagger/
      - bin/swagger_generate
      - ls
      name: "Swagger JSON"
