sudo: true
os: linux
language: go
go: ["1.11"]

env:
  global:
    - BUILD_COMMIT=$TRAVIS_COMMIT
    - BUILD_BRANCH=$TRAVIS_BRANCH
    - BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
    - BUILD_VERSION=$TRAVIS_TAG

before_install:
  - if [ -z "$BUILD_VERSION" ]; then
      export BUILD_VERSION=$(
        curl -s -H "Authorization:token $GIT_RELEASES_API_KEY"
        https://api.github.com/repos/${TRAVIS_REPO_SLUG}/releases |
        jq -r '( first(.[]  | select(.prerelease == true)) ) | .tag_name');
    fi

cache:
  directories:
    - vendor

stages:
  - dep-cache
  - test
  - name: build
    if: (type != pull_request AND branch = master AND tag IS blank) OR tag IS present
  - name: release-dev
    if: type != pull_request AND branch = master AND tag IS blank
  - name: release
    if: tag IS present

jobs:
  include:
    # Dependencies cache stage
    - stage: dep-cache
      name: "Vendor update"
      script:
        - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        - dep ensure

    # Test stage
    - stage: test
      script: bin/test
      name: "Unit tests"

    - script: bin/builder_run bin/check_golint
      name: "golint check"

    - script: bin/builder_run bin/check_goimports
      name: "goimports check"

    - script: bin/check_license
      name: "license check"

    - script: bin/check_govet
      name: "govet check"

    # Build artifacts
    - stage: build
      script:
      - go get github.com/go-swagger/go-swagger
      - bin/swagger generate spec --base-path=./cmd/mysterium_node/ -o ./tequilapi_spec.json --scan-models
      name: "Swagger JSON"
